apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b0cu5mwj6-go
  janus-idp.io/tekton: b0cu5mwj6-go
  backstage.io/kubernetes-id: b0cu5mwj6-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: b0cu5mwj6-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
