apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: b0cu5mwj6-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:95c6db105b8f674d01be5cab1ad4a76ca74f76eb@sha256:2b1f0395a8ac590ca9407902c624ccbd43ff63f8c75519617b2568d0e8b5bf9d
          name: container-image
